
INSERT INTO prodi (nama) VALUES ("Informatika");
INSERT INTO prodi (nama) VALUES ("Sistem Informasi");

INSERT INTO semester (nama) VALUES ("20192");

INSERT INTO tim (nama, semester_id, prodi_id) VALUES ("TI1",5,1);
INSERT INTO tim (nama, semester_id, prodi_id) VALUES ("TI2",5,1);
INSERT INTO tim (nama, semester_id, prodi_id) VALUES ("TI3",5,1);
INSERT INTO tim (nama, semester_id, prodi_id) VALUES ("TI4",5,1);
INSERT INTO tim (nama, semester_id, prodi_id) VALUES ("TI5",5,1);
INSERT INTO tim (nama, semester_id, prodi_id) VALUES ("TI6",5,1);
INSERT INTO tim (nama, semester_id, prodi_id) VALUES ("SI1",5,2);
INSERT INTO tim (nama, semester_id, prodi_id) VALUES ("SI2",5,2);
INSERT INTO tim (nama, semester_id, prodi_id) VALUES ("SI3",5,2);

INSERT INTO tim (nama, semester_id, prodi_id) VALUES ("Merkurius",7,1);
INSERT INTO tim (nama, semester_id, prodi_id) VALUES ("Venus",7,1);
INSERT INTO tim (nama, semester_id, prodi_id) VALUES ("Bumi",7,1);
INSERT INTO tim (nama, semester_id, prodi_id) VALUES ("Mars",7,1);
INSERT INTO tim (nama, semester_id, prodi_id) VALUES ("Jupiter",7,1);
INSERT INTO tim (nama, semester_id, prodi_id) VALUES ("Saturnus",7,1);
INSERT INTO tim (nama, semester_id, prodi_id) VALUES ("Uranus",7,2);
INSERT INTO tim (nama, semester_id, prodi_id) VALUES ("Neptunus",7,2);
INSERT INTO tim (nama, semester_id, prodi_id) VALUES ("Pluto",7,2);

INSERT INTO sprint (nama,tgl_mulai,tgl_selesai) VALUES ("sprint 1",CURRENT_DATE(),CURRENT_DATE());
INSERT INTO sprint (nama,tgl_mulai,tgl_selesai) VALUES ("sprint 2",CURRENT_DATE(),CURRENT_DATE());
INSERT INTO sprint (nama,tgl_mulai,tgl_selesai) VALUES ("sprint 3",CURRENT_DATE(),CURRENT_DATE());
INSERT INTO sprint (nama,tgl_mulai,tgl_selesai) VALUES ("sprint 4",CURRENT_DATE(),CURRENT_DATE());
INSERT INTO sprint (nama,tgl_mulai,tgl_selesai) VALUES ("sprint 5",CURRENT_DATE(),CURRENT_DATE());
INSERT INTO sprint (nama,tgl_mulai,tgl_selesai) VALUES ("sprint 6",CURRENT_DATE(),CURRENT_DATE());

INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,1,1);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (90,1,2);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (95,1,3);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (95,1,4);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (95,1,5);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (95,1,6);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (98,2,1);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (97,2,2);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,2,3);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,2,4);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,2,5);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,2,6);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (90,3,1);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (99,3,2);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (90,3,3);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,3,4);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,3,5);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,3,6);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (92,4,1);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (95,4,2);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (97,4,3);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,4,4);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,4,5);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,4,6);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (93,5,1);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (92,5,2);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (90,5,3);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,5,4);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,5,5);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,5,6);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (98,6,1);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (99,6,2);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (92,6,3);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,6,4);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,6,5);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,6,6);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (93,7,1);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (91,7,2);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (90,7,3);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,7,4);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,7,5);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,7,6);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (92,8,1);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (95,8,2);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (90,8,3);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,8,4);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,8,5);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,8,6);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (95,9,1);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (90,9,2);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (90,9,3);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,9,4);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,9,5);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,9,6);

INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,10,1);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (90,10,2);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (95,10,3);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (95,10,4);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (95,10,5);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (95,10,6);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (95,11,1);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (90,11,2);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (90,11,3);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,11,4);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,11,5);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,11,6);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (98,12,1);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (97,12,2);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,12,3);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,12,4);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,12,5);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,12,6);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (90,13,1);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (99,13,2);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (90,13,3);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,13,4);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,13,5);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,13,6);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (92,14,1);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (95,14,2);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (97,14,3);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,14,4);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,14,5);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,14,6);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (93,15,1);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (92,15,2);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (90,15,3);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,15,4);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,15,5);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,15,6);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (98,16,1);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (99,16,2);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (92,16,3);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,16,4);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,16,5);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,16,6);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (93,17,1);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (91,17,2);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (90,17,3);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,17,4);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,17,5);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,17,6);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (92,18,1);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (95,18,2);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (90,18,3);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,18,4);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,18,5);
INSERT INTO nilai_sprint (nilai,tim_id,sprint_id) VALUES (100,18,6);


INSERT INTO user (name,nim,tlahir,tgllahir,prodi_id,gender,email,nohp,role) VALUES ("Nafu","0110217070","Bandung","1999-09-09",1,"Wanita","nafu@gmail.com","088972543525","mahasiswa");
INSERT INTO user (name,nim,tlahir,tgllahir,prodi_id,gender,email,nohp,role) VALUES ("Chai","0110217955","Bandung","1999-08-11",1,"Pria","chai@gmail.com","088976242425","mahasiswa");
INSERT INTO user (name,nim,tlahir,tgllahir,prodi_id,gender,email,nohp,role) VALUES ("Fathan","0110217055","Jakarta","1999-07-25",1,"Pria","fathan@gmail.com","08897624224","mahasiswa");
INSERT INTO user (name,nim,tlahir,tgllahir,prodi_id,gender,email,nohp,role) VALUES ("Fazri","0110217036","Jakarta","1999-04-13",1,"Pria","fazri@gmail.com","088976389685","mahasiswa");
INSERT INTO user (name,nim,tlahir,tgllahir,prodi_id,gender,email,nohp,role) VALUES ("Ilham","0110217001","Medan","1999-01-01",1,"Pria","ilham@gmail.com","08897215056","mahasiswa");
INSERT INTO user (name,nim,tlahir,tgllahir,prodi_id,gender,email,nohp,role) VALUES ("Huda","0110215333","Bandung","1999-05-07",1,"Pria","huda@gmail.com","0889707614","mahasiswa");
INSERT INTO user (name,nim,tlahir,tgllahir,prodi_id,gender,email,nohp,role) VALUES ("Farel","0110217888","Jakarta","1999-11-09",1,"Pria","farel@gmail.com","0889856417","mahasiswa");
INSERT INTO user (name,nim,tlahir,tgllahir,prodi_id,gender,email,nohp,role) VALUES ("Mairat","0110217966","Medan","1999-10-09",1,"Pria","mairat@gmail.com","0889752674745","mahasiswa");
INSERT INTO user (name,nim,tlahir,tgllahir,prodi_id,gender,email,nohp,role) VALUES ("Jessie","0110217877","Surabaya","1999-11-14",2,"Wanita","jessie@gmail.com","088975242420","mahasiswa");
INSERT INTO user (name,nim,tlahir,tgllahir,prodi_id,gender,email,nohp,role) VALUES ("Usamah","0110217855","Banten","1999-02-15",2,"Pria","usamah@gmail.com","0889752234002","mahasiswa");
INSERT INTO user (name,nim,tlahir,tgllahir,prodi_id,gender,email,nohp,role) VALUES ("Wiranto","0110217899","Cirebon","1999-09-27",2,"Pria","wiranto@gmail.com","08897599874","mahasiswa");
INSERT INTO user (name,nim,tlahir,tgllahir,prodi_id,gender,email,nohp,role) VALUES ("Malik","0110217807","Lampung","1999-07-08",2,"Pria","malik@gmail.com","088971123145","mahasiswa");
INSERT INTO user (name,nidn,tlahir,tgllahir,gender,email,nohp,role) VALUES ("Reza","022617890432","Palembang","1986-01-19","Pria","reza@gmail.com","08951456899","dosen");
INSERT INTO user (name,nidn,tlahir,tgllahir,gender,email,nohp,role) VALUES ("Hilmi","022098723412","Semarang","1984-09-17","Pria","hilmi@gmail.com","0853225252119","dosen");
INSERT INTO user (name,nidn,tlahir,tgllahir,gender,email,nohp,role) VALUES ("Nasrul","022051234567","Medan","1980-10-10","Pria","nasrul@gmail.com","08894419007","dosen");
INSERT INTO user (name,tlahir,tgllahir,gender,email,nohp,role) VALUES ("Admin","Medan","1980-10-10","Pria","admin@gmail.com","08894419007","admin");

-- INSERT INTO nilai_sprint (point_sprint,nilai_dosen_sprint,nilai_sprint,tim_id,sprint_id) VALUES (5,90,1,1);

INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-2.5,13,1,1,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (5,13,1,2,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (10,13,1,3,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (7.5,13,1,4,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-7.5,13,1,5,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (0,13,1,6,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-2.5,13,2,1,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (5,13,2,2,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-2.5,13,2,3,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (0,13,2,4,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-2.5,13,2,5,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (0,13,2,6,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (0,13,3,1,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-2.5,13,3,2,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (0,13,3,3,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (15,13,3,4,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-7.5,13,3,5,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (5,13,3,6,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (0,13,4,1,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (5,13,4,2,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-7.5,13,4,3,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-2.5,13,4,4,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (10,13,4,5,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-2.5,13,4,6,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-7.5,13,5,1,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-2.5,13,5,2,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (10,13,5,3,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-2.5,13,5,4,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-7.5,13,5,5,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (0,13,5,6,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-2.5,13,6,1,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-7.5,13,6,2,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-7.50,13,6,3,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (0,13,6,4,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (7.5,13,6,5,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (0,13,6,6,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (0,13,7,1,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-2.5,13,7,2,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (10,13,7,3,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (0,13,7,4,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-2.5,13,7,5,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-7.5,13,7,6,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (15,13,8,1,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (0,13,8,2,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (5,13,8,3,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-10,13,8,4,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (0,13,8,5,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (5,13,8,6,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (0,13,9,1,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (5,13,9,2,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (10,13,9,3,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (0,13,9,4,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (10,13,9,5,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (5,13,9,6,"");

INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-2.5,13,10,1,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (5,13,10,2,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (10,13,10,3,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (7.5,13,10,4,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-7.5,13,10,5,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (0,13,10,6,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (0,13,11,1,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (5,13,11,2,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (10,13,11,3,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (0,13,11,4,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (10,13,11,5,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (5,13,11,6,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-2.5,13,12,1,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (5,13,12,6,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-2.5,13,12,3,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (0,13,12,4,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-2.5,13,12,5,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (0,13,12,6,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (0,13,13,1,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-2.5,13,13,2,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (0,13,13,3,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (15,13,13,4,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-7.5,13,13,5,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (5,13,13,6,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (0,13,14,1,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (5,13,14,2,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-7.5,13,14,3,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-2.5,13,14,4,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (10,13,14,5,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-2.5,13,14,6,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-7.5,13,15,1,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-2.5,13,15,2,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (10,13,15,3,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-2.5,13,15,4,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-7.5,13,15,5,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (0,13,15,6,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-2.5,13,16,1,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-7.5,13,16,2,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-7.50,13,16,3,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (0,13,16,4,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (7.5,13,16,5,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (0,13,16,6,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (0,13,17,1,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-2.5,13,17,2,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (10,13,17,3,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (0,13,17,4,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-2.5,13,17,5,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-7.5,13,17,6,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (15,13,18,1,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (0,13,18,2,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (5,13,18,3,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (-10,13,18,4,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (0,13,18,5,"");
INSERT INTO point_tim (point,user_id,tim_id,sprint_id,keterangan) VALUES (5,13,18,6,"");


INSERT INTO tim_member (tim_id, mahasiswa_id,semester_id) VALUES (1,1,5);
INSERT INTO tim_member (tim_id, mahasiswa_id,semester_id) VALUES (1,2,5);
INSERT INTO tim_member (tim_id, mahasiswa_id,semester_id) VALUES (2,3,5);
INSERT INTO tim_member (tim_id, mahasiswa_id,semester_id) VALUES (3,4,5);
INSERT INTO tim_member (tim_id, mahasiswa_id,semester_id) VALUES (4,5,5);
INSERT INTO tim_member (tim_id, mahasiswa_id,semester_id) VALUES (5,6,5);
INSERT INTO tim_member (tim_id, mahasiswa_id,semester_id) VALUES (5,7,5);
INSERT INTO tim_member (tim_id, mahasiswa_id,semester_id) VALUES (6,8,5);
INSERT INTO tim_member (tim_id, mahasiswa_id,semester_id) VALUES (7,9,5);
INSERT INTO tim_member (tim_id, mahasiswa_id,semester_id) VALUES (7,10,5);
INSERT INTO tim_member (tim_id, mahasiswa_id,semester_id) VALUES (8,11,5);
INSERT INTO tim_member (tim_id, mahasiswa_id,semester_id) VALUES (9,12,5);

INSERT INTO tim_member (tim_id, mahasiswa_id,semester_id) VALUES (3,1,7);
INSERT INTO tim_member (tim_id, mahasiswa_id,semester_id) VALUES (3,2,7);

INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (-3,14,1,1,"Terlambat Hadir,Tidak mengikuti daily meeting,Bermain game dan sosial media");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (-2,14,1,2,"Terlambat Hadir,Tidak mengikuti daily meeting");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (-1,14,1,3,"Tidak mengikuti penuh waktu");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,1,4,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,1,5,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,1,6,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,2,1,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,2,2,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,2,3,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (-1,14,2,4,"Bermain game dan sosial media");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,2,5,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,2,6,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (-1,14,3,1,"Terlambat Hadir");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (-1,14,3,2,"Bermain game dan sosial media");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (-1,14,3,3,"Tidak mengikuti daily meeting");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,3,4,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,3,5,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,3,6,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,4,1,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,4,2,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,4,3,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (-1,14,4,4,"Berpakaian tidak sesuai ketentuan");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,4,5,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,4,6,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,5,1,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,5,2,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (-1,14,5,3,"Tidak mengikuti daily meeting");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,5,4,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,5,5,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,5,6,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,6,1,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,6,2,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (-1,15,6,3,"Berpakaian tidak sesuai ketentuan");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,6,4,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (-1,14,6,5,"Berpakaian tidak sesuai ketentuan");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,6,6,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (-1,15,7,1,"Terlambat Hadir");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,7,2,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,15,7,3,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,7,4,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,7,5,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,7,6,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (-1,15,8,1,"Terlambat Hadir");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (-1,14,8,2,"Berpakaian tidak sesuai ketentuan");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (-1,14,8,3,"Terlambat Hadir");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,8,4,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,8,5,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,8,6,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (-1,14,9,1,"Bermain game dan sosial media");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,9,2,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,15,9,3,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,9,4,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,9,5,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,9,6,"");

INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (-3,14,14,1,"Terlambat Hadir,Tidak mengikuti daily meeting,Bermain game dan sosial media");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (-2,14,14,2,"Terlambat Hadir,Tidak mengikuti daily meeting");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (-1,14,14,3,"Tidak mengikuti penuh waktu");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,14,4,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,14,5,"");
INSERT INTO point_member (point,dosen_scrum_master_id,tim_member_id,sprint_id,keterangan) VALUES (0,14,14,6,"");

INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,100,1,1);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,90,1,2);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,95,1,3);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,95,1,4);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,95,1,5);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,95,1,6);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,98,2,1);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,97,2,2);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,100,2,3);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,100,2,4);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,100,2,5);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,100,2,6);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,90,3,1);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,99,3,2);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,90,3,3);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,100,3,4);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,100,3,5);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,100,3,6);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,92,4,1);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,95,4,2);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,97,4,3);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,100,4,4);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,100,4,5);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,100,4,6);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,93,5,1);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,92,5,2);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,90,5,3);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,100,5,4);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,100,5,5);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,100,5,6);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,98,6,1);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,99,6,2);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,92,6,3);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,100,6,4);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,100,6,5);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,100,6,6);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,93,7,1);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,91,7,2);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,90,7,3);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,100,7,4);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,100,7,5);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,100,7,6);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,92,8,1);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,95,8,2);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,90,8,3);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,100,8,4);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,100,8,5);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,100,8,6);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,95,9,1);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,90,9,2);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,90,9,3);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,100,9,4);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,100,9,5);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,100,9,6);

INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,100,12,1);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,90,12,2);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,95,12,3);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,95,12,4);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,95,12,5);
INSERT INTO nilai_tim (nilai_tim,final_skor,tim_id,sprint_id) VALUES (0,95,12,6);

INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,1,1,1);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (99,1,2,2);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,1,3,3);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,1,4,4);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,1,5,5);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,1,6,6);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,2,1,7);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (99,2,2,8);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (99,2,3,9);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,2,4,10);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,2,5,11);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,2,6,12);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,3,1,13);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,3,2,14);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,3,3,15);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,3,4,16);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,3,5,17);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,3,6,18);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,4,1,19);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,4,2,20);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,4,3,21);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,4,4,22);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,4,5,23);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,4,6,24);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,5,1,25);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,5,2,26);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,5,3,27);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,5,4,28);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,5,5,29);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,5,6,30);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,6,1,31);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,6,2,32);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,6,3,33);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,7,1,34);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,7,2,35);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,7,3,36);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,7,4,37);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,7,5,38);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,7,6,39);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,8,1,40);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,8,2,41);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,8,3,42);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,8,4,43);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,8,5,44);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,8,6,45);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,9,1,46);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,9,2,47);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,9,3,48);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,9,4,49);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,9,5,50);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,9,6,51);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,10,1,52);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,10,2,53);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,10,3,54);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,10,4,);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,10,5,);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,10,6,);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,11,1,);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,11,2,);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,11,3,);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,11,4,);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,11,5,);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,11,6,);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,12,1,);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,12,2,);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,12,3,);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,12,4,);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,12,5,);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,12,6,);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,13,1,);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,13,2,);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,13,3,);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,13,4,);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,13,5,);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,13,6,);

INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (100,14,1,55);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (99,14,2,56);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,14,3,57);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,14,4,58);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,14,5,59);
INSERT INTO nilai_member (skor_member,tim_member_id,sprint_id,skor_tim_id) VALUES (97,14,6,60);
